---
title: "Makefile"
author: "Mariana Llamas-Cendon"
date: "10/26/2016"
output: 
  html_document:
    keep_md: TRUE
---

```{r}

setwd("~/Desktop/git_repositories/CaseStudy")
```

```{r cache=FALSE}

source("Data/gatherGDP.R") 

### This file contains the code to:
#### Download and read raw data set Gross Gross Domestic Product 
#### The original file was downloaded from: https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv
#### Initialize a new data frame to contain raw data, called GdpData
#### Explore data to obtain its dimension, variable names, value types and number of rows to compare with the data set that this will be merged into: EducData.
#### Change names for the two variables of interest in this analysis from: X, X.1 to "CountryCode" and "GDP.Ranking".
```

```{r cache=FALSE}

source("Data/gatherEduc.R")

### This file contains code to:
#### Dowload and read raw data EducationStats.
#### The original file was downloaded from: https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv
#### Initialize a new data frame to contain raw data, called EducData.
#### Explore data to obtain its dimension, variable names, value types and number of rows to compare with the data set that this will be merged into.
```

```{r cache=FALSE}

source("Data/Merge.R")

### This file contains code to:
#### Merge GdpData and EducData by "CountryCode" into one new data frame called geData.
#### Explore data to obtain data frame's dimension, variable names, value types, number of rows and test the existence of NAs.
#### Eliminate NAs present on variable GDP.Ranking.
#### Coercion of value type for GDP.Ranking from character to numeric.
```

```{r cache=FALSE}

source("Analysis/Analysis.R")

### This file contains code to:
#### Initialize new data frame named ge.sorted, to sort variable GDP.Ranking in descending order.
#### Obtain the country in the 13th place after the sorting.
#### Calculate the mean for GDP.Rankings by the variable Income.group.
#### Plot the GDP.Ranking for all of the countries by Income.Group.
#### Cut GDP.Ranking into 5 separate quantile groups and create a table of GDP.Ranking vs. Income.Group.
```







